### ISSUE TITLE
Is there a way to change the Tasker System Time?

### ISSUE THREAD

**Issue by bazarnov** [opsxcq/tasker#12]
Hi, Is there any way to change the Tasker's time for certain time zones? Are there any config options along with docker-compose?
What time zone is default one?

Thanks!

**Comment by gerardsyd** [comment]
Did you work this out? Thanks!

**Comment by bazarnov** [comment]
Stopped using this lib, since it's not maintained as expected.

**Comment by opsxcq** [comment]
> What time zone is default one?

If running inside a container, UTC timezone is the default (it is docker's default), unless you configure (`/etc/localtime` or `TZ` variable).
