### ISSUE TITLE
Python run script inside docker-compose using Tasker

### ISSUE THREAD

**Issue by monetree** [opsxcq/tasker#13]
I am trying to run a python script but, getting below error. no such file  or directory.

`            tasker_1   | 2021-09-14 04:30:00.952 DEBUG 7 --- [pool-2-thread-1] sh.strm.tasker.schedule.SchedulerSetup   : Task helloFromPython output
            tasker_1   | 2021-09-14 04:30:00.953 DEBUG 7 --- [pool-2-thread-1] sh.strm.tasker.schedule.SchedulerSetup   : python: can't open file '/sweeper.py': [Errno 2] No such file or directory`

    `tasker:
        image: strm/tasker
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
        configuration: |
            schedule:
                - every: minute
                task: helloFromPython
            tasks:
                docker:
                    - name: helloFromPython
                    image: python:3-slim
                    script:
                        - python /sweeper.py`

`

Here is my service of docker-compose file. 
and I am following below link but there is an option to print in python only.
But, I wants to run a python file.

    https://github.com/opsxcq/tasker/blob/master/docker-compose.yml

**Comment by opsxcq** [comment]
You need to map the script inside the container, `tasker` will create another container based on the definition that you describe, and this container should have the script mapped inside.
