### ISSUE TITLE
How can I see the collected log

### ISSUE THREAD

**Issue by zjtzjtzjt201** [opsxcq/tasker#8]
`tasker_1  | 2019-08-30 03:09:00.172  INFO 6 --- [pool-2-thread-1] sh.strm.tasker.runner.DockerTaskRunner   : Starting container 6f06f408474cbe2cc59a981c55d5bf958fe49acaef460a205627571f00887de2 for task test_main`

`tasker_1  | 2019-08-30 03:09:00.172  INFO 6 --- [pool-2-thread-1] c.s.docker.client.DefaultDockerClient    : Starting container with Id: 6f06f408474cbe2cc59a981c55d5bf958fe49acaef460a205627571f00887de2`

`tasker_1  | 2019-08-30 03:09:04.811  INFO 6 --- [pool-2-thread-1] sh.strm.tasker.runner.DockerTaskRunner   : Container 6f06f408474cbe2cc59a981c55d5bf958fe49acaef460a205627571f00887de2 finished with exit code 0`

`tasker_1  | 2019-08-30 03:09:04.811  INFO 6 --- [pool-2-thread-1] sh.strm.tasker.runner.DockerTaskRunner   : Collecting container logs for 6f06f408474cbe2cc59a981c55d5bf958fe49acaef460a205627571f00887de2`

`tasker_1  | 2019-08-30 03:09:04.813  INFO 6 --- [pool-2-thread-1] sh.strm.tasker.runner.DockerTaskRunner   : Removing finished container 6f06f408474cbe2cc59a981c55d5bf958fe49acaef460a205627571f00887de2`

`tasker_1  | 2019-08-30 03:09:04.839  INFO 6 --- [pool-2-thread-1] sh.strm.tasker.runner.DockerTaskRunner   : Task test_main took 4839`

1. Tasker is really nice and convenient to set the schedule task, but I have a questiion. When task running, as you can see above, python script `test_main` and I set logging level INFO. Every time Tasker run a task by creating a new container, but I want more information about how my task being processing. I see Tasker may collect the container logs, so how can i see this collected logs ?

**Comment by CarMoreno** [comment]
I would like to know if you figured out how to see the logs, @zjtzjtzjt201

**Comment by opsxcq** [comment]
The logs are used for notifications, but I would recommend using Loki or something else if you want to centralize the logs. An example of how to centralize your logs (if you use ansible) https://github.com/opsxcq/ansible-role-linux-server/blob/master/tasks/monitoring.yml#L29
